name: PR Comment

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  stale-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check for stale PRs
        id: stale-prs
        run: |
          last_updated=$(date -d "$(jq -r '.pull_request.updated_at' $GITHUB_EVENT_PATH)" +%s)
          now=$(date +%s)
          days_since_update=$(( (now - last_updated) / 86400 ))
          echo "Days since last update: $days_since_update"
          if [ $days_since_update -ge 7 ]; then
            echo "::set-output name=stale_pr_number::${{ github.event.pull_request.number }}"
          else
            echo "::set-output name=stale_pr_number::"
          fi

      - name: Add stale comment
        if: ${{ steps.stale-prs.outputs.stale_pr_number != '' }}
        run: |
          COMMENT="It seems there has been no activity on this PR for more than a week. Please review or provide updates."
          echo "$COMMENT"
          # Posting comment via GitHub API
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\": \"$COMMENT\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ steps.stale-prs.outputs.stale_pr_number }}/comments"
