
name: Stale PR Comment v3

on:
  schedule:
    - cron: '*/1 * * * *' # Runs every 2 minutes for testing purposes


jobs:
  stale-pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository

        uses: actions/checkout@v3 # Updated to use Node.js 20

      - name: Fetch Open PRs
        run: |
          pr_data=$(gh pr list --state open --json number,updatedAt)
          echo "pr_data=$pr_data" >> $GITHUB_ENV

        uses: actions/checkout@v2

      - name: Check for stale PRs
        id: stale-prs
        run: |

          now=$(date +%s)
          stale_prs=$(echo "$pr_data" | jq -r '.[] | select((now - (.updatedAt | fromdateiso8601 | mktime)) > (7 * 24 * 60 * 60)) | .number')
          echo "stale_pr_numbers=$stale_prs" >> $GITHUB_ENV

      - name: Add stale comment
        if: ${{ env.stale_pr_numbers != '' }}
        run: |
          for pr in ${{ env.stale_pr_numbers }}; do
            COMMENT="It seems there has been no activity on this PR for more than a week. Please review or provide updates."
            echo "$COMMENT"
            gh pr comment $pr -b "$COMMENT"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          last_updated=$(date -d "$(jq -r '.pull_request.updated_at' $GITHUB_EVENT_PATH)" +%s)
          now=$(date +%s)
          days_since_update=$(( (now - last_updated) / 86400 ))
          echo "Days since last update: $days_since_update"
          if [ $days_since_update -ge 7 ]; then
            echo "::set-output name=stale_pr_number::${{ github.event.pull_request.number }}"
          else
            echo "::set-output name=stale_pr_number::"
          fi
      - name: Add stale comment
        if: ${{ steps.stale-prs.outputs.stale_pr_number != '' }}
        run: |
          COMMENT="It seems there has been no activity on this PR for more than a week. Please review or provide updates."
          echo "$COMMENT"
          # Posting comment via GitHub API
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\": \"$COMMENT\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ steps.stale-prs.outputs.stale_pr_number }}/comments"

          
